<?xml version="1.0" encoding="utf-8"?><!DOCTYPE template [

<!ELEMENT template (farm*)>
  <!ELEMENT farm (goods_type, farm_name, farm_logo?, farm_picture, farm_description, url, address, phone+, delivery, goods+)>
     
  <!ELEMENT goods_type (#PCDATA)>
  <!ELEMENT farm_name (#PCDATA)>
  <!ELEMENT farm_logo (#PCDATA)>
  <!ELEMENT farm_picture (#PCDATA)>
  <!ELEMENT farm_description (#PCDATA)>
  <!ELEMENT url (#PCDATA)>
  <!ELEMENT address (#PCDATA)>
  <!ELEMENT phone (#PCDATA)>
  <!ELEMENT delivery 
	(min_price, deli_fee)>
  <!ELEMENT min_price (#PCDATA)>
  <!ELEMENT deli_fee (#PCDATA)>
  <!ELEMENT goods 
	(goods_name, goods_pic)>
  <!ELEMENT goods_name (#PCDATA)>
  <!ELEMENT goods_pic (#PCDATA)>
]>

<template>
	<farm>
		<goods_type>Grains</goods_type>
		<farm_name>Oxfordshire Farm</farm_name>
		<farm_logo></farm_logo>
		<farm_picture>img/farm4.png</farm_picture>
		<farm_description></farm_description>
		<url>https://www.oxfordshirefarm.com.au/</url>
		<address>138 Gillards Road, Pokolbin, NSW</address>
		<phone>0491 570 158</phone>
		<phone>1900 654 322</phone>
		<delivery>
				<min_price></min_price>
				<deli_fee></deli_fee>
		</delivery>
		<goods>
				<goods_name></goods_name>
				<goods_pic></goods_pic>
		</goods>
	</farm>
	
	<farm>
		<goods_type>Dried Fruit</goods_type>
		<farm_name>Bolwalla Farm</farm_name>
		<farm_logo></farm_logo>
		<farm_picture>img/farm5.png</farm_picture>
		<farm_description></farm_description>
		<url>https://www.bolwallafarm.com.au/</url>
		<address>712 Wollombi Road, Broke, NSW</address>
		<phone>0491 570 159</phone>
		<phone>1900 654 325</phone>
		<delivery>
				<min_price></min_price>
				<deli_fee></deli_fee>
		</delivery>
		<goods>
				<goods_name></goods_name>
				<goods_pic></goods_pic>
		</goods>
	</farm>
	
	<farm>
		<goods_type>Seeds</goods_type>
		<farm_name>Sandy Hollow Farm</farm_name>
		<farm_logo></farm_logo>
		<farm_picture>img/farm6.png</farm_picture>
		<farm_description></farm_description>
		<url>https://www.sandyhollowfarm.com.au/</url>
		<address>197 Mount Dangar Road, Sandy Hollow, NSW</address>
		<phone>0491 570 160</phone>
		<phone>1900 654 330</phone>
		<delivery>
				<min_price></min_price>
				<deli_fee></deli_fee>
		</delivery>
		<goods>
				<goods_name></goods_name>
				<goods_pic></goods_pic>
		</goods>
	</farm>
</template>	