<?xml version="1.0" encoding="utf-8"?><!DOCTYPE template [

<!ELEMENT template (farm*)>
  <!ELEMENT farm (goods_type, farm_name, farm_logo?, farm_picture, farm_description, url, address, phone+, delivery, goods+)>
     
  <!ELEMENT goods_type (#PCDATA)>
  <!ELEMENT farm_name (#PCDATA)>
  <!ELEMENT farm_logo (#PCDATA)>
  <!ELEMENT farm_picture (#PCDATA)>
  <!ELEMENT farm_description (#PCDATA)>
  <!ELEMENT url (#PCDATA)>
  <!ELEMENT address (#PCDATA)>
  <!ELEMENT phone (#PCDATA)>
  <!ELEMENT delivery 
	(min_price, deli_fee)>
  <!ELEMENT min_price (#PCDATA)>
  <!ELEMENT deli_fee (#PCDATA)>
  <!ELEMENT goods 
	(goods_name, goods_pic)>
  <!ELEMENT goods_name (#PCDATA)>
  <!ELEMENT goods_pic (#PCDATA)>
]>

<template>
	<farm>
		<goods_type></goods_type>
		<farm_name></farm_name>
		<farm_logo></farm_logo>
		<farm_picture></farm_picture>
		<farm_description></farm_description>
		<url></url>
		<address></address>
		<phone></phone>
		<delivery>
				<min_price></min_price>
				<deli_fee></deli_fee>
		</delivery>
		<goods>
				<goods_name></goods_name>
				<goods_pic></goods_pic>
		</goods>
	</farm>
</template>	